#' Makes a table with certain sequencies in sample and their frequencies.
#'
#' @param S A set of lags in \eqn{1:d}.
#' @param j A lag \eqn{j \in (1:d) \setminus S}.
#' @param base_Sja A table generated by base_Sja.
#' @param lenX The length of sample vector.
#' @param d The chains order.
#'
#' @return A table with sequencies x indexed by \eqn{S\cup j}, their frequencies and the MLE estimator of the transition probabilities.
#' @importFrom dplyr %>%
#'
base_Sj <- function(S,j,base_Sja,lenX,d){
  Sj <- sort(c(S,j),decreasing = TRUE)
  if ( is.numeric(Sj) ) {
    base_Sj <- base_Sja %>%
                  dplyr::group_by_at(paste0("x",Sj)) %>%
                  dplyr::summarise(Nx_Sj=sum(Nxa_Sj), .groups="drop")
    base_Sj
  }else{
    matrix(c(0,lenX-d),ncol=2)
  }
}
