#' A table with the frequency of sample sequences
#'
#' Creates a table with the frequencies of the sequences in the sample.
#'
#' @param S A subset of \eqn{1:d}.
#' @param j An element \eqn{j \in (1:d) \setminus S}.
#' @param freqTab A table generated by the [freqTab()] function.
#' @param lenX The length of sample vector.
#' @param d The chains order.
#'
#' @return A table with sequences x indexed by \eqn{{-S} U {-j}}, their frequencies and the MLE estimator of the transition probabilities.
#' @importFrom dplyr %>%
#'
freqTabSj <- function(S,j,freqTab,lenX,d){
  Sj <- sort(c(S,j),decreasing = TRUE)
  if ( is.numeric(Sj) ) {
    freqTabSj <- freqTab %>%
                  dplyr::group_by_at(paste0("x",Sj)) %>%
                  dplyr::summarise(Nx_Sj=sum(Nxa_Sj), .groups="drop")
    freqTabSj
  }else{
    matrix(c(0,lenX-d),ncol=2)
  }
}
